In [1]:
def reverse(array):
    arr = array.copy()
    start = 0
    end   = len(arr)-1
    while start<end:
        arr[start],arr[end] = arr[end],arr[start]
        start+=1
        end-=1
    return arr


In [2]:
array = [1,2,3,4,5,6]
reverse(array)

[6, 5, 4, 3, 2, 1]

In [3]:
def reverse_subarray(array,start,end):
    arr = array.copy()
    while start<end:
        arr[start],arr[end]= arr[end],arr[start]
        start+=1
        end-=1
    return arr

In [4]:
reverse_subarray(array,2,4)

[1, 2, 5, 4, 3, 6]

In [5]:

array

[1, 2, 3, 4, 5, 6]

In [6]:
def rotation_array(array,k):
    temp = array.copy()
    new = temp.copy()
    n = len(array)
    for i in range(n):
        new[(i+k)%n] = temp[i]
    return new



In [7]:
array = [3,2,9,6,5,8]
rotation_array(array,3)

[6, 5, 8, 3, 2, 9]

In [8]:
# without extra space
def rotation_array_space(array,k):
    arr = array.copy()
    n = len(arr)
    subset_a = arr[n-k:]
    subset_b = arr[:n-k]
    return subset_a +subset_b

In [9]:
rotation_array_space(array,3)

[6, 5, 8, 3, 2, 9]

In [10]:
def rotation_array_without_space(array,k):
    n = len(array)
    k = k % n
    start = 0
    end = n -1
    while start<end:
        array[start],array[end] = array[end],array[start]
        start+=1
        end-=1
    start = 0
    end = k-1
    while start<end:
        array[start],array[end] = array[end],array[start]
        start+=1
        end-=1
    start = k
    end = len(array)-1
    while start<end:
        array[start],array[end] = array[end],array[start]
        start+=1
        end-=1
    return array



In [11]:
array = [3,2,9,6,5,8]
rotation_array_without_space(array,6)

[3, 2, 9, 6, 5, 8]

In [12]:
import numpy as np

array = np.array(range(1,17)).reshape(4,4)
array

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16]])

In [13]:
def spiral_printing(array):
    top,left = 0,0
    bottom,right = array.shape[0]-1,array.shape[1]-1
    while (top<=bottom)&(left<=right) :
        # left to right
        #print(top,left,bottom,right)
        #print("Left to Right",end=" ")
        for i in range(left,right+1):

            print(array[top][i],end=" ")
        top+=1
        # top to bottom
        #print("Top to Bottom",end=" ")
        for i in range(top,bottom+1):

            print(array[i][right],end=" ")
        right-=1
        # right to left
        #print("Right to Left",end=" ")
        for i in range(right,left-1,-1):

            print(array[bottom][i],end=" ")
        bottom-=1
        # bottom to up
        #print("Bottom to up",end=" ")
        for i in range(bottom,top-1,-1):

            print(array[i][left],end=" ")
        left+=1



In [14]:
spiral_printing(array)

1 2 3 4 8 12 16 15 14 13 9 5 6 7 11 10 

In [15]:
array = np.arange(1,10).reshape(3,3)
array

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [16]:
def transpose(array):
    m= array.shape[0]
    for i in range(m):
        for j in range(i):
            array[i,j],array[j,i] = array[j,i],array[i,j]


In [17]:
def reverse(array):
    start = 0
    end = len(array)-1
    while start<end:
        array[start],array[end] = array[end],array[start]
        start+=1
        end-=1


In [18]:
def rotate(array):
    m = array.shape[0]-1
    transpose(array)
    for i in range(m):
        reverse(array[i,:])

In [19]:
array

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

# Given a String you need to find the subsequence of "ag" exist in the string

In [20]:
string = "abcgag"
ans = 0
a = 0
for c in string:
    if c == "a":
        a+=1
    if c =="g":
        ans+=a
print(ans)


3


In [21]:
import numpy as np

In [22]:
listofzeros = np.zeros((5,5),dtype=int)
listofzeros

array([[0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0]])

In [23]:
for row in range(len(listofzeros)):
    inc = 1
    for col in range(len(listofzeros)-1,len(listofzeros)-row-2,-1):
        listofzeros[row][col]  = inc
        inc+=1

In [24]:
listofzeros

array([[0, 0, 0, 0, 1],
       [0, 0, 0, 2, 1],
       [0, 0, 3, 2, 1],
       [0, 4, 3, 2, 1],
       [5, 4, 3, 2, 1]])

# Given an integer array, find the size of the smallest subarray contain the minimum and  maximum

In [25]:
import sys

In [26]:
~sys.maxsize

-9223372036854775808

In [91]:
array = [1,2,6,4,5,1,2,1,3,6,3,3,2,1]

In [92]:
maxi = ~sys.maxsize
mini = sys.maxsize
for i in range(len(array)):
    if array[i] > maxi:
        maxi = array[i]
    if array[i] < mini:
        mini = array[i]

In [93]:
print(mini, maxi)

1 6


In [94]:
ans = sys.maxsize
for i in range(len(array)):
    # find the minimum
    if array[i] == mini:
        # if we found the min then find the nearest maximum
        for j in range(i+1,len(array)):
            if array[j] == maxi:
                ans = min(ans, j - i + 1)
                break
    if array[i] == maxi:
        for j in range(i+1,len(array)):
            if array[j] == mini:
                ans = min(ans,j-i+1)
                break

In [95]:
ans

3

In [96]:
max_index = sys.maxsize
min_index = sys.maxsize
ans = sys.maxsize
for i in range(len(array)-1,-1,-1):
    if array[i] == maxi:
        max_index = i
        ans = min(ans, min_index - max_index + 1)

    if array[i] == mini:
        min_index = i
        ans = min(ans,max_index-min_index+1)

In [97]:
ans

3

In [100]:
max_index = -1
min_index = -1
ans = len(array)
for i in range(len(array)):
    if array[i] == maxi:
        max_index = i
        if min_index != -1:
            ans = min(ans,max_index-min_index+1)


    if array[i] == mini:
        min_index = i
        if max_index != -1:
            ans = min(ans,min_index-max_index+1)

In [101]:
ans

3